config/routes.rb
G16Classwork::Application.routes.draw do
  root :to => 'classtests#index'  
  
  resources :studentanswers do
    collection do 
      post 'multiple_choice'
    end
  end

  resources :answers 

  resources :questions do
    collection do
      get 'lostandfound'
      get 'clone'
    end
    member do 
      get 'answers'
    end
  end

  resources :testtypes

  resources :studenttests do
    member do
      get 'state'
      get 'finish'
      get 'result'
      get 'result_details'
      get 'download'
      get 'refresh_points'
    end
    collection do
      get 'get_for_valuation'
      get 'results_for_teacher'
      get 'refresh_allpoints'
    end
  end

  resources :classtests do    
    member do
      get 'state'
      get 'students'
      get 'addstudents'
      get 'valuate_results'
      get 'valuate_single_question'
    end
  end

end

app/models/classtest.rb
class Classtest < ActiveRecord::Base
  attr_accessible :category, :description, :duration, :lecture_id, :title, :testtype_id

  validates :lecture_id, :testtype_id, :title, presence: true

  belongs_to :testtype
  has_many :events, class_name: "ClasstestEvent"
  has_many :studenttests

  after_create :initialize_studenttests

  CATEGORIES = %w(Multiplechoice Text Mixed Upload)

  ICON_STATES = {"new" => 'lock', "open" => "unlock", "canceled" => 'lock', 'shipped' => 'download', 'closed' => 'archive'}
  STATES = %w[new open canceled shipped closed]
  delegate :new?, :open?, :canceled?, :shipped?, :closed?, to: :current_state

  def self.open_tests
    #joins(:events).merge TestEvent.with_last_state("open")
    joins(:events).where("classtest_events.id IN (SELECT MAX(id) FROM classtest_events GROUP BY test_id) AND state = 'open'")
  end

  def current_state
    (events.last.try(:state) || STATES.first).inquiry
  end

  def change(state)
    events.create! state: state
  end

  def search_for_missing_studenttests
    studenttests = Studenttest.where(:classtest_id => self.id)
    studenttest_student_ids = studenttests.map {|s| s.student_id }
    ls_ids = $redis.smembers "students_#{self.lecture_id}"
    lecture_student_ids = ls_ids.map {|id| id.to_i}
    student_without_test = lecture_student_ids - studenttest_student_ids
  end

  def initialize_studenttests
    student_ids = $redis.smembers "students_#{self.lecture_id}"
    student_ids.each do |student_id|
      studenttest = Studenttest.create(:classtest_id => self.id, :student_id => student_id.to_s)
      if self.category == "Upload"
        Studentanswer.generate_studentanswer(studenttest.id)
      else
        Studentanswer.generate_studentanswers(studenttest.id)
      end
    end
  end
end

app/controllers/classtests_controller.rb
class ClasstestsController < ApplicationController

  def students
    @classtest = Classtest.find(params[:id])
    @studenttests = Studenttest.where(:classtest_id => @classtest.id)
    @student_without_test = @classtest.search_for_missing_studenttests
    respond_to do |format|
      format.html
      format.json { render json: @classtests }
    end
  end

  def valuate_results
    @studenttests = Studenttest.where(classtest_id: params[:classtest_id])
    @classtest = Classtest.find(params[:id])
    @questions = @classtest.testtype.questions.order(:id)
  end

  def valuate_single_question
    @classtest_id = params[:id]
    @question = Question.find(params[:question_id])
    @studenttests = Studenttest.where(classtest_id: params[:id])
    @studentanswers = {}
    @studenttests.each do |studenttest|
      @studentanswers[studenttest.student_id] = Studentanswer.where(question_id: params[:question_id], studenttest_id: studenttest.id).first || Studentanswer.create(question_id: params[:question_id], studenttest_id: studenttest.id) 
    end
  end

  def addstudents
    classtest = Classtest.find(params[:id])
    student_without_test = classtest.search_for_missing_studenttests
    student_without_test.each do |student_id|
      studenttest = Studenttest.create(:classtest_id => classtest.id, :student_id => student_id.to_s) 
      Studentanswer.generate_studentanswers(studenttest.id)
    end
    redirect_to students_classtest_url(classtest.id)
  end

  def state
    test = Classtest.find(params[:id])
    test.change(params[:state])
    @classtests = Classtest.all
    respond_to do |format|
      format.html {redirect_to classtests_url}
      format.json { render json: @classtests }
    end    
  end

  def index
    if request.format == "application/json" || @current_user.admin?
      @classtests = Classtest.all
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @classtests }
      end
    else
      #http://localhost:3001/studenttests?lecture=KuA_Fit3h
      redirect_to studenttests_url(:lecture => params[:lecture])
    end

  end

  def show
    @classtest = Classtest.find(params[:id])
    @lecture = Lecture.find(@classtest.lecture_id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @classtest }
    end
  end

  # GET /tests/new
  # GET /tests/new.json
  def new
    @classtest = Classtest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @classtest }
    end
  end

  # GET /tests/1/edit
  def edit
    @classtest = Classtest.find(params[:id])
  end

  # POST /tests
  # POST /tests.json
  def create
    @classtest = Classtest.new(params[:classtest])

    respond_to do |format|
      if @classtest.save
        #UPDATE fuer Hauptseite VALUATIONS
        Valuation.create(:title => @classtest.title, :lecture_id => @classtest.lecture_id, :classtest_id => @classtest.id, :mark_type => 'Klausur')
        format.html { redirect_to @classtest, notice: 'Classtest was successfully created.' }
        format.json { render json: @classtest, status: :created, location: @classtest }
      else
        format.html { render action: "new" }
        format.json { render json: @classtest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tests/1
  # PUT /tests/1.json
  def update
    @classtest = Classtest.find(params[:id])

    respond_to do |format|
      if @classtest.update_attributes(params[:classtest])
        format.html { redirect_to @classtest, notice: 'Classtest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @classtest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @classtest = Classtest.find(params[:id])
    @classtest.destroy

    respond_to do |format|
      format.html { redirect_to classtests_url }
      format.json { head :no_content }
    end
  end
end

app/views/classtests/_form.html.erb
<%= simple_form_for(@classtest) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :category, collection: Classtest::CATEGORIES %>
    <%= f.input :testtype_id, collection: Testtype.all %>
    <%= f.input :lecture_id, collection: JSON.parse($redis.get("lectures")).map{|l| [l['title'],l['id']] } %>
    <%= f.input :duration %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/classtests/edit.html.erb
<h1>Editing test</h1>

<%= render 'form' %>

<%= link_to 'Show', @classtest %> |
<%= link_to 'Back', classtests_path %>

app/views/classtests/index.html.erb
<% if @classtests.blank? %>
  <div class="panel callout radius">
    <h3>Keine Tests vorhanden.</h3>
  </div>
<% else %>
  <h3>Tests <%= @title %></h3>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Category</th>
        <th>Lecture</th>
        <th>Duration</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @classtests.each do |classtest| %>
      <tr>
        <td><%= classtest.title %></td>
        <td><%= classtest.description %></td>
        <td><%= classtest.category %></td>
        <td><%= classtest.lecture_id %></td>
        <td><%= classtest.duration %></td>
        <% if current_user.admin? %>
          <td>
            <nobr>
            <% Classtest::STATES.each do |state| %>
              <%= classtest.current_state == state ? raw("<i title='#{state}' class='fi-#{Classtest::ICON_STATES[state]} dark-green icon-normal'></i></span>") : link_to(raw("<i class='fi-#{Classtest::ICON_STATES[state]} dark-red icon-normal'></i>"),state_classtest_path(classtest,:state => state), :title => state)  %>  
            <% end %>
            </nobr>
          </td>
          <td>
            <nobr>
              <%= link_to raw("<i class='fi-torsos dark-green icon-normal'></i>"), students_classtest_path(classtest), title: "Studentenverteilung überprüfen. Alle Schüler diesem Test zugeordnet?" %>
              <%= link_to raw("<i class='fi-eye dark-green icon-normal'></i>"), results_for_teacher_studenttests_path(classtest_id: classtest.id), title: "Schülerergebnisse für diesen Test ansehen" %>
              <%= link_to raw("<i class='fi-pencil dark-green icon-normal'></i>"), edit_classtest_path(classtest) %>
              <%= link_to raw("<i class='fi-trash dark-red icon-normal'></i>"), classtest, method: :delete, data: { confirm: 'Are you sure?' } %>
            </nobr>
          </td>
        <% else %>
          <td>
            <% if classtest.current_state == 'open' %>
              <%= link_to(classtest.current_state, classtest_path(classtest,:state => classtest.current_state)) %>
            <% else %>
              <%= classtest.current_state %>
            <% end %>

          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
  </table>
<% end %>
<% if current_user.admin? %>
  <div class="panel callout radius">
    <h5><%= link_to "Neuen Test anlegen", new_classtest_path %></h5>
  </div>
<% end %>

app/views/classtests/new.html.erb
<h1>New test</h1>

<%= render 'form' %>

<%= link_to 'Back', classtests_path %>

app/views/classtests/show.html.erb
<ul class="pricing-table">
  <li class="title"><%= @classtest.title %></li>
  <li class="description"><%= @classtest.description %></li>
  <li class="bullet-item">Testtyp: <%= @classtest.testtype.title %></li>
  <li class="bullet-item">Kurs: <%= @lecture.title unless @lecture.blank? %></li>
  <li class="bullet-item">Kategorie: <%= @classtest.category %></li>
  <li class="bullet-item">Dauer: <%= @classtest.duration %></li>
  <li class="cta-button">
    <%= link_to "Schuelerergebnisse", results_for_teacher_studenttests_path(classtest_id: @classtest.id), :class => "button" %>
    <%= link_to "Aufgabe zur Korrektur", valuate_results_classtest_path(@classtest.id), :class => "button" %>
  </li>
</ul>

<div class="panel callout radius">
  <h5><%= @classtest.studenttests.count %> Schülertests sind zugeordnet</h5>
  <ul class="inline-list">
    <li><%= link_to 'Edit', edit_classtest_path(@classtest) %></li>
    <li><%= link_to 'Alle anzeigen', classtests_path %></li>
  </ul>
</div>

app/views/classtests/students.html.erb
<ul class="pricing-table">
  <li class="title">Existierende Studenttests: <%= @classtest.title %></li>
  <li class="description"><%= @classtest.title %></li>
  <li class="bullet-item">
    <ul class="no-bullet">
      <% @studenttests.each do |studenttest| %>
        <li><%= $redis.get "userstudent_#{studenttest.student_id}" %></li>
      <% end %>
    </ul>
  </li>
</ul>

<hr />

<ul class="pricing-table">
  <li class="title">Fehlende Studenttests: <%= @classtest.title %></li>
  <li class="description"><%= @classtest.title %></li>
  <% if @student_without_test.empty? %>
    <li class="bullet-item"><h5>Allen Kursteilnehmern ist ein test zugeordnet</h5></li>
  <% else %>
    <li class="bullet-item"> 
      <ul class="no-bullet">
        <% @student_without_test.each do |id| %>
          <li><%= $redis.get "userstudent_#{id}" %></li>
        <% end %>
      </ul>
    </li>
    <li class="cta-button"><%= link_to 'Fehlende Tests anlegen', addstudents_classtest_path(@classtest),  :class => "button" %></li>
  <% end %>
</ul>

app/views/classtests/valuate_results.html.erb
<ul class="pricing-table">
  <li class="title"><%= @classtest.title %></li>
  <li class="description"><%= @classtest.description %></li>
  <li class="bullet-item">Testtyp: <%= @classtest.testtype.title %></li>
  <li class="bullet-item">Kurs: <%= @lecture.title unless @lecture.blank? %></li>
  <li class="bullet-item">Kategorie: <%= @classtest.category %></li>
</ul>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Typ</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.title %></td>
      <td><%= question.category %></td>
      <td>
        <% if question.category == 'Text' %>
          <%= link_to(raw("<i class='fi-pencil dark-green icon-big'></i>"), 
              valuate_single_question_classtest_path(@classtest.id, :question_id => question.id)) %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="panel callout radius">
  <h5><%= link_to "Alle Tests anzeigen", classtests_path %> |
  <%= link_to "Aufgaben zur Korrektur", valuate_results_classtest_path(@classtest.id) %></h5>
</div>

app/views/classtests/valuate_single_question.html.erb
<ul class="pricing-table">
  <li class="title">Maximale Punkte: <%= @question.points %></li>
  <li class="bullet-item"><%= @question.title %></li>
</ul>

<table>
  <thead>
    <tr>
      <th>Schueler</th>
      <th>Loesung</th>
      <th>Punkte</th>
    </tr>
  </thead>
  <tbody>
    <% @studentanswers.each do |key,item| %>
      <tr>
        <td valign="top"><strong><%= $redis.get "userstudent_#{key}" %></strong></td>
        <td><%= simple_format(item.result) if item && item.result %></td>
        <td>
          <%= best_in_place(item, :points, :nil => "Click") if item && item.points %><br />
          <%= item.functionality if item %> %
        </td>
      </tr>    
    <% end %>
  </tbody>
</table>

<div class="panel callout radius">
  <h5><%= link_to "Alle Fragen anzeigen", valuate_results_classtest_path(@classtest_id) %> |
  <%= link_to "Alle Schuelertests anzeigen", results_for_teacher_studenttests_path(classtest_id: @classtest_id) %></h5>
</div>