config/routes.rb
G16Classwork::Application.routes.draw do
  root :to => 'classtests#index'  
  
  resources :studentanswers do
    collection do 
      post 'multiple_choice'
    end
  end

  resources :answers 

  resources :questions do
    collection do
      get 'lostandfound'
      get 'clone'
    end
    member do 
      get 'answers'
    end
  end

  resources :testtypes

  resources :studenttests do
    member do
      get 'state'
      get 'finish'
      get 'result'
      get 'result_details'
      get 'download'
      get 'refresh_points'
    end
    collection do
      get 'get_for_valuation'
      get 'results_for_teacher'
      get 'refresh_allpoints'
    end
  end

  resources :classtests do    
    member do
      get 'state'
      get 'students'
      get 'addstudents'
      get 'valuate_results'
      get 'valuate_single_question'
    end
  end

end

app/controllers/testtypes_controller.rb
class TesttypesController < ApplicationController
  # GET /testtypes
  # GET /testtypes.json
  def index
    @testtypes = Testtype.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @testtypes }
    end
  end

  # GET /testtypes/1
  # GET /testtypes/1.json
  def show
    @testtype = Testtype.find(params[:id])
    @questions = Question.where(:testtype_id => @testtype.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @testtype }
    end
  end

  # GET /testtypes/new
  # GET /testtypes/new.json
  def new
    @testtype = Testtype.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @testtype }
    end
  end

  # GET /testtypes/1/edit
  def edit
    @testtype = Testtype.find(params[:id])
  end

  # POST /testtypes
  # POST /testtypes.json
  def create
    @testtype = Testtype.new(params[:testtype])

    respond_to do |format|
      if @testtype.save
        format.html { redirect_to @testtype, notice: 'Testtype was successfully created.' }
        format.json { render json: @testtype, status: :created, location: @testtype }
      else
        format.html { render action: "new" }
        format.json { render json: @testtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /testtypes/1
  # PUT /testtypes/1.json
  def update
    @testtype = Testtype.find(params[:id])

    respond_to do |format|
      if @testtype.update_attributes(params[:testtype])
        format.html { redirect_to @testtype, notice: 'Testtype was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @testtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testtypes/1
  # DELETE /testtypes/1.json
  def destroy
    @testtype = Testtype.find(params[:id])
    @testtype.destroy

    respond_to do |format|
      format.html { redirect_to testtypes_url }
      format.json { head :no_content }
    end
  end
end

app/views/testtypes/_form.html.erb
<%= simple_form_for(@testtype) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :coursetype, collection: Testtype::COURSES %>
    <%= f.input :title %>
    <%= f.input :description %>
    <fieldset>
      <b>Nur wenn eine Datei mit Fragen und Antworten per Dump integriert werden soll</b><br />
      <%= f.input :test_avatar, :as => :file %>
      <%= f.input :create_questions, :as => :radio_buttons %>
    </fieldset>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/testtypes/create.js.erb
    $('#window_modal').foundation('reveal', 'close');
    $('#append_question').append("<%= j render @question %>");

app/views/testtypes/edit.html.erb
<h1>Editing testtype</h1>

<%= render 'form' %>

<%= link_to 'Show', @testtype %> |
<%= link_to 'Back', testtypes_path %>

app/views/testtypes/index.html.erb
<h1>Listing testtypes</h1>

<table>
  <tr>
    <th>Coursetype</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @testtypes.each do |testtype| %>
  <tr>
    <td><%= testtype.coursetype %></td>
    <td><%= best_in_place testtype, :title %></td>
    <td><%= best_in_place testtype, :description, :type => :textarea %></td>
    <td><%= link_to raw("<i class='fi-eye dark-green icon-normal'></i>"), testtype %></td>
    <td><%= link_to raw("<i class='fi-pencil dark-green icon-normal'></i>"), edit_testtype_path(testtype) %></td>
    <td><%= link_to raw("<i class='fi-trash dark-green icon-normal'></i>"), testtype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<% if current_user.admin? %>
  <div class="panel callout radius">
    <h5><%= link_to "Neuen Test anlegen", new_testtype_path %></h5>
  </div>
<% end %>

app/views/testtypes/new.html.erb
<h1>New testtype</h1>

<%= render 'form' %>

<%= link_to 'Back', testtypes_path %>

app/views/testtypes/show.html.erb
<div data-alert class="alert-box info radius">
<%= link_to raw("<i class='fi-plus dark-blue icon-normal'></i> Neue Frage hinzufügen"), new_question_path(:testtype_id => @testtype.id), 
              :remote => true, 
              :html => 'data-reveal-id="day_modal" data-reveal-ajax="true"', 
              title: "Eine neue Frage zum Test hinzufügen." %>
  <a href="#" class="close">&times;</a>
</div>

<h3>Fragen von: <%= @testtype.title %> <span class="small-font" id="sum_points">(<%= @testtype.sum_points %> Punkte gesamt.)</span></h3>
<div id="window_modal" class="reveal-modal small" data-reveal></div>

<table class="datatable">
  <thead>
    <th>Titel</th>
    <th>Category</th>
    <th>R.</th>
    <th>P.</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <%= render :partial => 'questions/question', :object => question %>
    <% end %>
  </tbody>
</table>