config/routes.rb
G16Classwork::Application.routes.draw do
  root :to => 'classtests#index'  
  
  resources :studentanswers do
    collection do 
      post 'multiple_choice'
    end
  end

  resources :answers 

  resources :questions do
    collection do
      get 'lostandfound'
      get 'clone'
    end
    member do 
      get 'answers'
    end
  end

  resources :testtypes

  resources :studenttests do
    member do
      get 'state'
      get 'finish'
      get 'result'
      get 'result_details'
      get 'download'
      get 'refresh_points'
    end
    collection do
      get 'get_for_valuation'
      get 'results_for_teacher'
      get 'refresh_allpoints'
    end
  end

  resources :classtests do    
    member do
      get 'state'
      get 'students'
      get 'addstudents'
      get 'valuate_results'
      get 'valuate_single_question'
    end
  end

end

app/models/studenttest.rb
class Studenttest < ActiveRecord::Base
  attr_accessible :end, :points, :start, :student_id, :classtest_id, :result_file
  mount_uploader :result_file, TestAvatarUploader

  has_many :events, class_name: "StudenttestEvent"
  has_many :studentanswers, :dependent => :destroy
  belongs_to :classtest
  
  def sum_points
    studentanswers.sum(:points)
  end

  ICON_STATES = {"new" => 'lock', "started" => "unlock", "closed" => 'lock', 'shipped' => 'download'}
  STATES = %w[new started closed shipped ]
  delegate :new?, :started?, :closed?, :shipped?, to: :current_state

  def self.open_tests
    #joins(:events).merge TestEvent.with_last_state("open")
    joins(:events).where("studenttest_events.id IN (SELECT MAX(id) FROM studenttest_events GROUP BY studenttest_id) AND state = 'open'")
  end

  def current_state
    (events.last.try(:state) || STATES.first).inquiry
  end

  def change(state)
    events.create! state: state
  end

end

app/controllers/studenttests_controller.rb
class StudenttestsController < ApplicationController
  def state
    test = Studenttest.find(params[:id])
    test.change(params[:state])
    @classtests = Studenttest.all
    respond_to do |format|
      format.html {redirect_to studenttests_url}
      format.json { render json: @classtests }
    end    
  end

  def get_for_valuation
    @studenttest = Studenttest.where(:classtest_id => params[:params][:classtest_id], :student_id => params[:params][:student_id]).first
    respond_to do |format|
      format.json { render json: @studenttest }
    end
  end

  def finish
    @studenttest = Studenttest.find(params[:id])
    @studenttest.change("closed")
    @studenttest.update_attributes(:end => DateTime.now, :points => @studenttest.sum_points)
    valuation = Valuation.find(:all, :params => {:classtest_id => @studenttest.classtest_id})
    #raise valuation[0].id.to_yaml
    sv = Studentvaluation.create(:points => @studenttest.points, :studenttest_id => @studenttest.id, 
      :student_id => @studenttest.student_id, :valuation_id => valuation[0].id )
    #raise sv.to_yaml
    
    #sv.save
    redirect_to studenttests_url(:lecture => @studenttest.classtest.lecture_id), :notice => "Sie haben den Test absolviert. Wenn sich der Status auf 'shipped' aendert, koennen Sie das Ergebnis sehen."
  end
  def refresh_points
    @studenttest = Studenttest.find(params[:id])
    points = @studenttest.sum_points
    @studenttest.update_attribute(:points,points)
  end
  def refresh_allpoints
    @studenttests = Studenttest.where(classtest_id: params[:classtest_id])
    @studenttests.each do |studenttest|
      points = studenttest.sum_points
      studenttest.update_attribute(:points,points)
    end
    redirect_to results_for_teacher_studenttests_url(classtest_id: params[:classtest_id]), notice: "Punkte wurden aktualisiert"
  end
  def result_details
    @studenttest = Studenttest.find(params[:id])
    @studentanswers = Studentanswer.where(studenttest_id: params[:id]).order(:question_id)
  end
  def results_for_teacher
    @studenttests = Studenttest.where(classtest_id: params[:classtest_id])
  end

  def result
    @studenttest = Studenttest.find(params[:id])
    @studenttest.change("shipped")
    @questions = @studenttest.classtest.testtype.questions
    respond_to do |format|
      format.pdf do
        pdf = StudenttestPdf.new(@studenttest)
        send_data pdf.render, filename: "Testergebnis-#{current_user.login}-#{@studenttest.classtest.title}",
                            type: "application/pdf",
                            disposition: "inline"
      end
      format.html 
    end
  end

  def download
    @studenttest = Studenttest.find(params[:id])
    #raise @page.file.to_yaml
    send_file(@studenttest.result_file.path,
        :filename => File.basename(@studenttest.result_file.path),
        :disposition => 'attachment',
        :url_based_filename => true)
  end

  def index
    #if $redis.hget(@current_user.login.to_sym, :classwork_lecture).blank?
    #  @studenttests = nil
    @lecture = Lecture.find(params[:lecture])
    @classtests = Classtest.where(:lecture_id => @lecture.id)
    if @classtests
      classtest_ids = @classtests.map {|t| t.id}
      student_id = eval($redis.hget(:current_user, current_user.login.to_sym))["student_id"]
      @studenttests = Studenttest.where(:student_id => student_id, :classtest_id => classtest_ids)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @studenttests }
    end
  end

  def show
    @studenttest = Studenttest.find(params[:id])
    if @studenttest.current_state == 'closed' || @studenttest.current_state == 'shipped'
      redirect_to studenttests_url, :notice => "Der Status des angeforderten Tests laesst keine Bearbeitung zu."
    else
      if @studenttest.current_state == 'new'
        @studenttest.change("started")
        @studenttest.update_attributes(:start => DateTime.now, :end => nil, :points => 0)
      end
      if @studenttest.classtest.category == "Upload"
        render "upload"
      else
        Studentanswer.where(:studenttest_id => @studenttest.id).each do |sa|
          sa.update_attributes(:selected => false, :points => 0)
        end
        @questions = @studenttest.classtest.testtype.questions
        render "show"
      end
    end
  end

  # GET /studenttests/new
  # GET /studenttests/new.json
  def new
    @studenttest = Studenttest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @studenttest }
    end
  end

  def edit
    @studenttest = Studenttest.find(params[:id])
  end

  def create
    @studenttest = Studenttest.new(params[:studenttest])

    respond_to do |format|
      if @studenttest.save
        format.html { redirect_to @studenttest, notice: 'Studenttest was successfully created.' }
        format.json { render json: @studenttest, status: :created, location: @studenttest }
      else
        format.html { render action: "new" }
        format.json { render json: @studenttest.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @studenttest = Studenttest.find(params[:id])
    params[:studenttest][:end] = DateTime.now
    respond_to do |format|
      if @studenttest.update_attributes(params[:studenttest])
        format.html { redirect_to @studenttest, notice: 'Studenttest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @studenttest.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @studenttest = Studenttest.find(params[:id])
    @studenttest.destroy

    respond_to do |format|
      format.html { redirect_to studenttests_url }
      format.json { head :no_content }
    end
  end
end

app/views/studenttests/_form.html.erb
<%= simple_form_for(@studenttest) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :test_id %>
    <%= f.input :student_id %>
    <%= f.input :start %>
    <%= f.input :end %>
    <%= f.input :points %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/studenttests/edit.html.erb
<h1>Editing studenttest</h1>

<%= render 'form' %>

<%= link_to 'Show', @studenttest %> |
<%= link_to 'Back', studenttests_path %>

app/views/studenttests/index.html.erb
<% if @classtests.blank? %>
  <div class="panel callout radius">
    <h3>Keine Tests vorhanden.</h3>
  </div>
<% else %>
  <h3>Tests fuer Kurs: <%= @lecture.title %></h3>
  <table>
    <thead>
      <tr>
        <th>Titel</th>
        <th>Beschreibung</th>
        <th>Dauer</th>
        <th>Start</th>
        <th>Ende</th>
        <th>Punkte</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @studenttests.each do |studenttest| %>
      <tr>
        <td><%= studenttest.classtest.title %></td>
        <td><%= studenttest.classtest.description %></td>
        <td><%= studenttest.classtest.duration %></td>
        <td><%= studenttest.start %></td>
        <td><%= studenttest.end %></td>
        <td><%= studenttest.points %></td>
        <td>
          <nobr>
          <% Studenttest::STATES.each do |state| %>
            <% icon = studenttest.current_state == state ? "dark-blue" : "dark-red" %>
            <%= raw("<i title='#{state}' class='fi-#{Studenttest::ICON_STATES[state]} #{icon} icon-normal'></i></span>") %>  
          <% end %>
          </nobr>
        </td>
        <td>
          <% if studenttest.classtest.current_state == 'open' %>
            <% if studenttest.current_state == 'new' %>
              <%= link_to("Test starten", studenttest_path(studenttest)) %>
            <% elsif studenttest.current_state == 'started'%>
              <%= link_to("Test fortsetzen", studenttest_path(studenttest)) %>
            <% elsif studenttest.current_state == 'closed'%>
              Der Test kann nicht bearbeitet werden.
            <% end %>
          <% elsif studenttest.classtest.current_state == 'shipped'%>
            <%= link_to("Ergebnis", result_studenttest_path(studenttest)) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>
<% end %>

app/views/studenttests/new.html.erb
<h1>New studenttest</h1>

<%= render 'form' %>

<%= link_to 'Back', studenttests_path %>

app/views/studenttests/refresh_points.js.erb
$("#points_<%= @studenttest.id %>").html('<%= @studenttest.points %>');

app/views/studenttests/result.html.erb
<ul class="pricing-table">
  <li class="title"><%= @studenttest.classtest.title %></li>
  <li class="bullet-item">Erreichte Punktzahl: <%= @studenttest.points %> von 100</li>
  <li class="cta-button"><%= link_to "Test als PDF", result_studenttest_path(@studenttest,:format => 'pdf'), :class => "button" %></li>
</ul>

<table class="datatable">
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>
  <tbody>
  <% @questions.each do |question| %>
    <tr>
      <td>
        <%= question.title %><br />
        <table width="100%">
          <% @studenttest.studentanswers.where(:question_id => question.id).each do |sa| %>
            <tr>
              <td width="5%"><%= raw('<i class="fi-like dark-green icon-normal"></i>') if sa.answer.points > 0 %></td>
              <td width="5%"><%= raw('<i class="fi-checkbox dark-green icon-normal"></i>') if sa.selected %></td>
              <td><%= sa.answer.title %></td>
            </tr>
          <% end %>
        </table>
      </td>
      <td>

      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="panel callout radius">
  <h5><%= link_to "Test als PDF", result_studenttest_path(@studenttest,:format => 'pdf') %></h5>
</div>

app/views/studenttests/result_details.js.erb
$("#window_modal").html("<%= j(render(:partial => 'studentanswers/evaluate_answers')) %>");
$('#window_modal').foundation('reveal', 'open');

app/views/studenttests/results_for_teacher.html.erb
<% if @studenttests.blank? %>
  <div class="panel callout radius">
    <h3>Keine Tests vorhanden.</h3>
  </div>
<% else %>
  <h3>Tests fuer Kurs: <%= @studenttests.first.classtest.title %></h3>
  
  <div class="panel callout radius">
    <%= @studenttests.first.classtest.description %><br />
    Dauer: <%= @studenttests.first.classtest.duration %><br />
    <%= link_to "Alle Points aktualisieren", refresh_allpoints_studenttests_path(classtest_id: @studenttests.first.classtest_id) %>
  </div>

  <div id="window_modal" class="reveal-modal small" data-reveal></div>

  <table class="datatable">
    <thead>
      <tr>
        <th>Titel</th>
        <th>Start</th>
        <th>Ende</th>
        <th>Punkte</th>
        <th></th>
        <th>Note</th>
        <th>Details</th>
        <th>Datei</th>
      </tr>
    </thead>
    <tbody>
    <% @studenttests.each do |studenttest| %>
      <tr>
        <td><%= $redis.get "userstudent_#{studenttest.student_id}" %></td>
        <td><%= studenttest.start %></td>
        <td><%= studenttest.end %></td>
        <td id="points_<%= studenttest.id %>">
          <%= best_in_place studenttest, :points %>
        </td>
        <td>
          <%= link_to raw('<i class="fi-annotate dark-green icon-normal"></i>'),
              refresh_points_studenttest_path(studenttest.id),
              :remote => true, title: "Punkte aktualisieren." %>
        </td>
        <td><%= POINTS_TO_NOTE[studenttest.points] %></td>
        <td><%= link_to raw('<i class="fi-pencil dark-green icon-normal"></i>'),
              result_details_studenttest_path(studenttest.id),
              :remote => true, 
              :html => 'data-reveal-id="day_modal" data-reveal-ajax="true"', 
              title: "Testfragen zum Editieren im Detail." %>
        </td>
        <td><%= result_file_upload studenttest %>
        </td>
      </tr>
    <% end %>  
    </tbody>
  </table>
<% end %>

<div class="panel callout radius">
  <h5><%= link_to "Alle Tests anzeigen", classtests_path %> |
  <%= link_to "Aufgaben zur Korrektur", valuate_results_classtest_path(@studenttests.first.classtest_id) %></h5>
</div>

app/views/studenttests/show.html.erb
<ul class="pricing-table">
  <li class="title"><%= @studenttest.classtest.title %></li>
  <li class="cta-button"><%= link_to "Test beenden", finish_studenttest_path(@studenttest), :class => "button", 
        data: { confirm: 'Sicher?? Nach dem Beenden koennen Sie den Test nicht mehr bearbeiten'}  %></li>
</ul>

<div id="window_modal" class="reveal-modal small" data-reveal></div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Typ</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.title %></td>
      <td><%= question.category %></td>
      <td>
        <% if question.category == 'Multiplechoice' || question.category == 'MehrereAntworten' %>
          <%= link_to(raw("<i class='fi-pencil dark-green icon-big'></i>"), 
              studentanswers_path(:studenttest_id => @studenttest.id, :question_id => question.id), 
              :remote => true, :title => "Antworten anzeigen.",
              :html => 'data-reveal-id="day_modal" data-reveal-ajax="true"') %>
        <% else %>
          <%= link_to(raw("<i class='fi-pencil dark-green icon-big'></i>"), 
              edit_studentanswer_path(question, :studenttest_id => @studenttest.id, :question_id => question.id), 
              :remote => true, :title => "Antwort eingeben.",
              :html => 'data-reveal-id="day_modal" data-reveal-ajax="true"') %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="panel callout radius">
  <h5><%= link_to "Test beenden", finish_studenttest_path(@studenttest),
                        data: { confirm: 'Sicher?? Nach dem Beenden koennen Sie den Test nicht mehr bearbeiten'} %></h5>
</div>

app/views/studenttests/upload.html.erb
<ul class="pricing-table">
  <li class="title"><%= @studenttest.classtest.title %></li>
  
  <%= simple_form_for(@studenttest) do |f| %>
    <%= f.error_notification %>
      <li class="description">
        <div class="form-inputs">
          Upload Ihrer Arbeit:<br />
          <%= f.input :result_file, :as => :file %>
        </div>
      </li>
      <li class="cta-button">
        <div class="form-actions">
          <%= f.button :submit %>
        </div>
      </li>
    <% end %>
</ul>