config/routes.rb
G16Classwork::Application.routes.draw do
  root :to => 'classtests#index'  
  
  resources :studentanswers do
    collection do 
      post 'multiple_choice'
    end
  end

  resources :answers 

  resources :questions do
    collection do
      get 'lostandfound'
      get 'clone'
    end
    member do 
      get 'answers'
    end
  end

  resources :testtypes

  resources :studenttests do
    member do
      get 'state'
      get 'finish'
      get 'result'
      get 'result_details'
      get 'download'
      get 'refresh_points'
    end
    collection do
      get 'get_for_valuation'
      get 'results_for_teacher'
      get 'refresh_allpoints'
    end
  end

  resources :classtests do    
    member do
      get 'state'
      get 'students'
      get 'addstudents'
      get 'valuate_results'
      get 'valuate_single_question'
    end
  end

end

app/views/layouts/_navigation.html.erb
        <nav class="top-bar" data-topbar >
          <ul class="title-area">
            <li class="name">
              <h1><%= link_to 'G16', root_path %></h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li> 
          </ul>

          <section class="top-bar-section">
            <!-- Right Nav Section -->
            <ul class="right">
              <li class="active"><a href="#"></a></li>
            </ul>

            <!-- Left Nav Section -->
            <% if current_user.admin? %> 
              <ul class="left">
                <li class="has-dropdown">
                  <a href="#">TestTypes</a>
                  <ul class="dropdown">
                    <li><%= link_to 'Alle', testtypes_path %></li>
                    <li><%= link_to 'Neu', new_testtype_path %></li>
                    <% Testtype.order(:title).each do |test| %>
                      <li><%= link_to test.title, testtype_path(test.id) %></li>
                    <% end %>
                  </ul>
                </li>

                <li class="has-dropdown">
                  <a href="#">Tests</a>
                  <ul class="dropdown">
                    <li><%= link_to 'Alle', classtests_path %></li>
                    <li><%= link_to 'Neu', new_classtest_path %></li>
                    <% Classtest.order(:title).each do |classtest| %>
                      <li><%= link_to classtest.title, classtest_path(classtest.id) %></li>
                    <% end %>
                  </ul>
                </li>

                <li class="has-dropdown">
                  <a href="#">Kurse</a>
                  <ul class="dropdown">
                    <% $redis.lrange(:course_lectures, 0, -1).each do |lec| %>
                      <li><%= link_to lec, "#" %></li>
                    <% end %>
                  </ul>
                </li>
              </ul>
            <% else %>
              <ul class="left">
 
              </ul>

            <% end %>
            <ul class="right">
              <li class="active"><%= link_to "Zur Übersicht", root_path %></li>
            </ul>
          </section>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "G16 Klassenarbeiten" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="row">
    <div class="small-12 columns">
      <ul class="button-group right">
          <li><%= link_to "Zur Login Seite", "http://g16-hh.de", :class => "button tiny lightblue" %></li>
          <li><%= link_to "Log Out #{current_user.login}", "http://g16-hh.de/logout", :class => "button tiny lightblue " %></li>
      </ul>
      
      <%= image_tag('g16_logo-green.png', :size => '280x100', title: "Klassenarbeit - G16 Farmsen") %>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <span style="color:#e36a16; font-size:2em; border-bottom: 3px #79B578 solid;"  >Klassenarbeiten</span>
    </div>
    </div>
   
       
    <!-- NAV -->
    <div class="row">
      <div class="small-12 columns">
        <%= render 'layouts/navigation' if current_user %>      
      </div>
    </div>
   
   
    <!-- Main Page Content and Sidebar -->
     <div class="row">
      <div class="small-12 columns">
        <div id="flash-message">
          <% flash.each do |name, msg| %>
            <div data-alert class="alert-box <%= name %> radius"><%= msg %></div>
          <% end %>
        </div>

        <%= yield %>

      </div>
    </div>
   
    <!-- End Main Content and Sidebar -->
   
   
    <!-- Footer -->
   
    <footer class="row">
      <div class="large-12 columns">
        <hr />
        <div class="row">
          <div class="large-6 columns">
            <p>© Thomas Bogner 2014.</p>
          </div>
          <div class="large-6 columns">
            <ul class="inline-list right">
              <li><a href="http://www.g16hh.de/">G16 Farmsen</a></li>
              <li><a href="http://141.91.210.14/">G16 Moodle</a></li>
              <li><a href="https://www2.wibes.de">Wibes</a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <%= javascript_include_tag "application" %>
  </body>
</html>